name: book_adapter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  email_validator: ^2.0.1
  enum_to_string: ^2.0.1
  epubx: ^3.0.0-dev.3
  file_picker: ^4.1.3
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.0-dev.11
  http: ^0.13.4
  i18n_extension: ^4.1.0
  implicitly_animated_reorderable_list: ^0.4.1
  intl: ^0.17.0
  logger: ^1.1.0
  multi_screen_layout: ^2.0.0
  path_provider: ^2.0.1
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  sticky_headers: ^0.2.0
  flutter_hooks: ^0.18.0
  drag_select_grid_view: ^0.5.1

dev_dependencies:
  build_runner: ^2.1.2
  firebase_auth_mocks: ^0.8.1
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  mockito: ^5.0.16
  test: any

# Uncomment the flutter_icons section when adding an icon, then run
# flutter pub run flutter_launcher_icons:main
# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  #   - assets/svgs/
