name: book_adapter
description: A new Flutter project.
publish_to: "none"
version: 0.4.2+9

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.15
  dartz: ^0.10.1
  email_validator: ^2.0.1
  epubx: ^3.0.0
  epub_view: ^3.0.0
  file_picker: ^4.5.1
  # Not compatible with Firebase dart initialization
  # firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  i18n_extension: ^4.2.1
  implicitly_animated_reorderable_list: ^0.4.2
  # Use for date formatting
  # intl: ^0.17.0
  logger: ^1.1.0
  path_provider: ^2.0.10
  responsive_builder: ^0.4.2
  uuid: ^3.0.6
  flutter_hooks: ^0.18.3
  sliver_tools: ^0.2.6
  url_launcher: ^6.1.2
  flutter_update_dialog:
    path: ./packages/flutter_update_dialog
  package_info_plus: ^1.4.2
  oktoast: ^3.2.0
  app_installer: ^1.1.0
  dio: ^4.0.6
  permission_handler: ^9.2.0
  sticky_and_expandable_list: ^1.0.3
  crypto: ^3.0.1
  watcher: ^1.0.1
  auto_size_text: ^3.0.0
  equatable: ^2.0.3
  image: ^3.1.3
  async: ^2.8.2
  flutter_native_splash: ^2.1.6
  paged_html:
    path: ./packages/paged_html

dev_dependencies:
  build_runner: ^2.1.2
  firebase_auth_mocks: ^0.8.1
  fake_cloud_firestore: ^1.2.1
  firebase_storage_mocks: ^0.5.0
  flutter_gen_runner: ^4.1.5
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  mockito: ^5.1.0
  dependency_validator: ^3.1.2
  test: any
  integration_test:
    sdk: flutter

# Uncomment the flutter_icons section when adding an icon, then run
# flutter pub run flutter_launcher_icons:main
# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"
flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  # Disable generate when using build_runner
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
  #   - assets/svgs/
