// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyINx_wx2sPs3SBVNCg_gK4VSIixrTasg',
    appId: '1:1038050596871:android:eb6a22cca5fad5db8772a2',
    messagingSenderId: '1038050596871',
    projectId: 'bookadapter',
    storageBucket: 'bookadapter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYt6RM3K-jnxPwydpZ4FL4gzR6dLysaDU',
    appId: '1:1038050596871:ios:505bc03ad6e7dba28772a2',
    messagingSenderId: '1038050596871',
    projectId: 'bookadapter',
    storageBucket: 'bookadapter.appspot.com',
    iosClientId:
        '1038050596871-tu74adaj7p25gecriet7tgjv7adu0ml9.apps.googleusercontent.com',
    iosBundleId: 'com.bookAdapterTeam.bookAdapter',
  );
}
