name: flutter_update_dialog
description: A beautiful application version update dialog for flutter.You can customize your own version update pop-up window!
version: 2.0.0
homepage: https://github.com/xuexiangjys/flutter_update_dialog
repository: https://github.com/xuexiangjys/flutter_update_dialog
issue_tracker: https://github.com/xuexiangjys/flutter_update_dialog/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/
